#!/bin/bash

echo "================================"
echo "🧪 ollamaparser 테스트 명령어들"
echo "================================"
echo ""

echo "1️⃣기본 동작 (감지만)"
echo "Command:"
echo "  uv run ollamaparser-parse \\"
echo "    --pdf kpmg.pdf \\"
echo "    --out_dir ./test_output \\"
echo "    --detector fallback \\"
echo "    --ocr-provider none \\"
echo "    --vlm-provider none \\"
echo "    --page-end 1"
echo ""

echo "2️⃣ OCR 활성화 (페이지 전체)"
echo "Command:"
echo "  uv run ollamaparser-parse \\"
echo "    --pdf kpmg.pdf \\"
echo "    --out_dir ./test_output_ocr \\"
echo "    --detector fallback \\"
echo "    --ocr-provider deepseek-ollama \\"
echo "    --ocr-scope page \\"
echo "    --page-end 1"
echo ""

echo "3️⃣ VLM 활성화 (페이지 분석)"
echo "Command:"
echo "  uv run ollamaparser-parse \\"
echo "    --pdf kpmg.pdf \\"
echo "    --out_dir ./test_output_vlm \\"
echo "    --detector fallback \\"
echo "    --vlm-provider ollama-vlm \\"
echo "    --vlm-scope page \\"
echo "    --page-end 1"
echo ""

echo "4️⃣ OCR + VLM 함께 사용"
echo "Command:"
echo "  uv run ollamaparser-parse \\"
echo "    --pdf kpmg.pdf \\"
echo "    --out_dir ./test_output_full \\"
echo "    --detector fallback \\"
echo "    --ocr-provider deepseek-ollama \\"
echo "    --ocr-scope page \\"
echo "    --vlm-provider ollama-vlm \\"
echo "    --vlm-scope page \\"
echo "    --page-end 1"
echo ""

echo "5️⃣ 다른 VLM 모델 사용 (환경변수)"
echo "Command:"
echo "  VLM_MODEL=qwen3-vl:30b uv run ollamaparser-parse \\"
echo "    --pdf kpmg.pdf \\"
echo "    --out_dir ./test_output_qwen \\"
echo "    --detector fallback \\"
echo "    --vlm-provider ollama-vlm \\"
echo "    --vlm-scope page \\"
echo "    --page-end 1"
echo ""

echo "6️⃣ .env 파일로 모든 설정"
echo "먼저 .env 파일 수정:"
echo "  OCR_MODEL=deepseek-ocr:latest"
echo "  VLM_MODEL=qwen3-vl:30b"
echo "  OLLAMA_HOST=http://localhost:11434"
echo ""
echo "그 다음 실행:"
echo "  uv run ollamaparser-parse \\"
echo "    --pdf kpmg.pdf \\"
echo "    --out_dir ./test_output_env \\"
echo "    --detector fallback \\"
echo "    --ocr-provider deepseek-ollama \\"
echo "    --ocr-scope page \\"
echo "    --vlm-provider ollama-vlm \\"
echo "    --vlm-scope page \\"
echo "    --page-end 1"
echo ""

echo "================================"
echo "📊 출력 파일:"
echo "  test_output/out.md"
echo "  test_output/out.meta.json"
echo "  test_output/pages/page_0001.png"
echo "================================"
